###################################################
##  https://minecraft.fandom.com/wiki/Game_rule  ##
###################################################

worlds:
  hub:
    doDaylightCycle: false
    fallDamage: false
    keepInventory: true
    randomTickSpeed: 0
  # wildcard support
  'world_player_*':
    keepInventory: true